---
title: 'Bats: Sensor Performance'
author: "Hallie Rutten, Shelby Cline, Monae Scott"
date: '2022-06-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# basic read -----
source('dataRead-bats.R')
bats <- bats %>% 
  rename( siteID = sensor) %>% 
  select(-LATITUDE,-LONGITUDE)

# sensor data read -----
source('dataRead-sensorDates.R')
  
# join bats and sensor site data -----
bats <- left_join(bats,sensorDates, by=c('siteID','DATE'))
```





# EXPLORATORY:

## Sensor Performance Trends

```{r}
# recording effort by date -----
sensor.days <- sensorDates %>% 
  group_by(DATE) %>% 
  summarize( nSensors = n() )

ggplot( sensor.days ) +
  geom_line( aes(x=DATE, y=nSensors) )

ggplot( sensor.days ) +
  geom_point( aes(x=DATE, y=nSensors), alpha=0.4 )
```

```{r}
# monitor accuracy -----
IDs <- unique(bats$AUTO.ID)
noID <- c('NoID','NoId')
IDbats <- IDs[which(! IDs %in% noID & IDs!='Noise')]

monitor.acc <- bats %>% 
  group_by(monitor,year) %>% 
  summarize( nBats = sum(as.numeric(AUTO.ID %in% IDbats)),
             unID = sum(as.numeric(AUTO.ID %in% noID)),
             noise = sum(as.numeric(grepl("Noise",AUTO.ID,ignore.case=TRUE))),
             total = sum(nBats,unID,noise),
             p.unID = unID/total, 
             p.noise = noise/total )

ggplot( monitor.acc ) +
  geom_col( aes(x=monitor, y=p.unID, fill=p.unID) ) +
  facet_wrap(~year) +
  theme(legend.position='none') +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title="Monitor 'no ID' observations",
       x="Monitor number", y="proportion of unidentified bats",
       caption="DataLab 2022")

ggplot( monitor.acc ) +
  geom_col( aes(x=monitor, y=p.noise, fill=-p.noise) ) +
  facet_wrap(~year) +
  theme(legend.position='none') +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(title="Monitor 'noise' observations",
       x="Monitor number", y="proportion of noise",
       caption="DataLab 2022")
```





# DASHBOARD PREP:

## Sensor Performance

```{r}
# set stand-in input vars -----

#use unique() to use all years, others for specific or single years
  selectedYears <- unique(bats$year)
  #selectedYears <- c(2020,2021)
  #selectedYears <- 2019

#use unique() to use all compartments, others for specific or single compartments
  selectedComps <- unique(bats$COMPARTMENT)
  #selectedComps <- c("C20","C22","C33")
  #selectedComps <- "C50"

#use whichever is selected (single input choice)
  param <- 'noise'
  #param <- 'noID'

#use whichever is selected (single input choice)
  equip <- 'monitor'
  #equip <- 'mic'

#use whichever is selected (single input choice)
  #wrapVar <- 'year'
  wrapVar <- 'none'
```

```{r}
# filter data by stand-in input vars -----
bats.sub <- bats %>% 
  filter( year %in% selectedYears,
          COMPARTMENT %in% selectedComps )

IDs <- unique(bats$AUTO.ID)
IDbats <- IDs[which( !grepl('noID|Noise',IDs,ignore.case=TRUE) )]

if(equip == 'monitor'){
  if(wrapVar == 'year'){
    bats.sub <- bats.sub %>% 
      group_by(monitor,year) %>% 
      summarize( nBats = sum(as.numeric(AUTO.ID %in% IDbats)),
                 unID  = sum(as.numeric(grepl('noID',IDs,ignore.case=TRUE))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID,ignore.case=TRUE))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
  }
  if(wrapVar == 'none'){
    bats.sub <- bats.sub %>% 
      group_by(monitor) %>% 
      summarize( nBats = sum(as.numeric(AUTO.ID %in% IDbats)),
                 unID  = sum(as.numeric(grepl('noID',IDs,ignore.case=TRUE))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID,ignore.case=TRUE))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
  }
}
if(equip == 'mic'){
  if(wrapVar == 'year'){
    bats.sub <- bats.sub %>% 
      group_by(mic,year) %>% 
      summarize( nBats = sum(as.numeric(AUTO.ID %in% IDbats)),
                 unID  = sum(as.numeric(grepl('noID',IDs,ignore.case=TRUE))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID,ignore.case=TRUE))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
  }
  if(wrapVar == 'none'){
    bats.sub <- bats.sub %>% 
      group_by(mic) %>% 
      summarize( nBats = sum(as.numeric(AUTO.ID %in% IDbats)),
                 unID  = sum(as.numeric(grepl('noID',IDs,ignore.case=TRUE))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID,ignore.case=TRUE))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
  }
}
```

```{r}
# graph with stand-in input vars -----

if(equip == 'monitor'){
  if(param == 'noise'){
    sensor.plot <- ggplot( bats.sub ) +
      geom_col( aes(x=monitor, y=p.noise, fill=-p.noise) ) +
      theme(legend.position='none') +
      theme(axis.text.x = element_text(angle = 90))
  }
  if(param == 'noID'){
    sensor.plot <- ggplot( bats.sub ) +
      geom_col( aes(x=monitor, y=p.unID, fill=-p.unID) ) +
      theme(legend.position='none') +
      theme(axis.text.x = element_text(angle = 90))
  }
}

if(equip == 'mic'){
  if(param == 'noise'){
    sensor.plot <- ggplot( bats.sub ) +
      geom_col( aes(x=mic, y=p.noise, fill=-p.noise) ) +
      theme(legend.position='none') +
      theme(axis.text.x = element_text(angle = 90))
  }
  if(param == 'noID'){
    sensor.plot <- ggplot( bats.sub ) +
      geom_col( aes(x=mic, y=p.unID, fill=-p.unID) ) +
      theme(legend.position='none') +
      theme(axis.text.x = element_text(angle = 90))
  }
}

if(wrapVar == 'year'){
  sensor.plot + facet_wrap(~year)
}
if(wrapVar == 'none'){
  sensor.plot
}
```





# DASHBOARD PREP ROUND 2:


## Sampling Activity

```{r}
selectedYears <- unique(bats$year)
selectedComps <- unique(bats$COMPARTMENT)

bats.sub <- bats %>% 
  filter( year %in% selectedYears,
          COMPARTMENT %in% selectedComps )

sampling.granularity <- 'month'
sampling.style <- 'line'
```

```{r}
    if(sampling.granularity == 'year'){
      sensorDates <- sensorDates %>% mutate( div=year(DATE) )
    } else if(sampling.granularity == 'month'){
      sensorDates <- sensorDates %>% 
        mutate( div=as.Date(paste(year(DATE),month(DATE),1,sep='-')) )
    }else if(sampling.granularity == 'day'){
      sensorDates <- sensorDates %>% mutate( div=DATE )
    }
    ```

```{r}
    sampling.days <- sensorDates %>% 
      group_by(div) %>% 
      summarize( nSites = n() )
    ```

```{r}
    sample.plot <- ggplot( sampling.days, aes(x=div, y=nSites) )
    
    if(sampling.style == 'line'){
      sample.plot <- sample.plot + geom_line()
    }
    if(sampling.style == 'points'){
      sample.plot <- sample.plot + geom_point(alpha=0.4)
    }
    
    sample.plot +
      labs(title="Sampling Activity",
           x=sampling.granularity, y="N Sites",
           caption="Sewanee Bat Study, DataLab 2022")
```


## Sensor accuracy

```{r}
selectedYears <- unique(bats$year)
selectedComps <- unique(bats$COMPARTMENT)

bats.sub <- bats %>% 
  filter( year %in% selectedYears,
          COMPARTMENT %in% selectedComps )

sensor.wrapVar <- 'year'
sensor.ob <- 'Noise'
```

```{r}
if(sensor.wrapVar == 'year'){
  bats.monitor <- bats.sub %>% mutate( wrapV=year)
}

if(sensor.wrapVar == 'none'){
  bats.monitor <- bats.sub %>% 
      group_by(monitor) %>% 
      summarize( nBats = sum(as.numeric(!grepl('no.ID|Noise',AUTO.ID))),
                 unID  = sum(as.numeric(grepl('no.ID',AUTO.ID))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
} else {
  bats.monitor <- bats.monitor %>% 
      group_by(monitor,wrapV) %>% 
      summarize( nBats = sum(as.numeric(!grepl('no.ID|Noise',AUTO.ID))),
                 unID  = sum(as.numeric(grepl('no.ID',AUTO.ID))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
}
```

```{r}
if(sensor.ob == 'Noise'){
  monitor.p <- ggplot( bats.monitor, aes(x=monitor, y=p.noise, fill=-p.noise) )
} else {
  monitor.p <- ggplot( bats.monitor, aes(x=monitor, y=p.unID, fill=-p.unID) )
}

monitor.p <- monitor.p +
  geom_col() +
  theme(legend.position='none') +
  theme(axis.text.x = element_text(angle = 90))

if(sensor.wrapVar == 'none'){
  monitor.p
} else {
  monitor.p + facet_wrap(~wrapV)
}
```




## Mic accuracy

```{r}
selectedYears <- unique(bats$year)
selectedComps <- unique(bats$COMPARTMENT)

bats.sub <- bats %>% 
  filter( year %in% selectedYears,
          COMPARTMENT %in% selectedComps )

sensor.wrapVar <- 'year'
sensor.ob <- 'Noise'
```

```{r}
if(sensor.wrapVar == 'year'){
  bats.mic <- bats.sub %>% mutate( wrapV=year)
}

if(sensor.wrapVar == 'none'){
  bats.mic <- bats.sub %>% 
      group_by(mic) %>% 
      summarize( nBats = sum(as.numeric(!grepl('no.ID|Noise',AUTO.ID))),
                 unID  = sum(as.numeric(grepl('no.ID',AUTO.ID))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
} else {
  bats.mic <- bats.mic %>% 
      group_by(mic,wrapV) %>% 
      summarize( nBats = sum(as.numeric(!grepl('no.ID|Noise',AUTO.ID))),
                 unID  = sum(as.numeric(grepl('no.ID',AUTO.ID))),
                 noise = sum(as.numeric(grepl("Noise",AUTO.ID))),
                 total = n(),
                 p.unID = unID/total, 
                 p.noise = noise/total )
}
```

```{r}
if(sensor.ob == 'Noise'){
  mic.p <- ggplot( bats.mic, aes(x=mic, y=p.noise, fill=-p.noise) )
} else {
  mic.p <- ggplot( bats.mic, aes(x=mic, y=p.unID, fill=-p.unID) )
}

mic.p <- mic.p +
  geom_col() +
  theme(legend.position='none') +
  theme(axis.text.x = element_text(angle = 90))

if(sensor.wrapVar == 'none'){
  mic.p
} else {
  mic.p + facet_wrap(~wrapV)
}
```
