---
title: 'Bats: Diversity Trends'
author: "Shelby Cline"
date: '2022-06-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# basic read -----
source('dataRead-bats.R')
bats <- bats %>% 
  rename( siteID = sensor) %>% 
  select(-LATITUDE,-LONGITUDE)

# sensor data read -----
source('dataRead-sensorDates.R')
  
# join bats and sensor site data -----
bats <- left_join(bats,sensorDates, by=c('siteID','DATE'))
  
library(readxl)
batspecies <- read_excel("BatSpecies.xlsx")
#left join the 2 datasets
bats<- left_join(bats,batspecies, by="AUTO.ID")

# group common names
bats <- bats %>% 
  mutate( group_common = ifelse(species_group=="MYOTIS", "Genus Myotis", Common),
          group_common = ifelse(species_group=="EPTFUS.LASNOC",
                                "Big Brown Bat/Silver-haired Bat", group_common),
          group_common = ifelse(species_group=="LASBOR.NYCHUM",
                                "Red Bat/Evening Bat", group_common) )
```

# Diversity (species) Trends

Big Graph

```{r}
  
# by changing the x-axis value, we can create a couple of different graphs to include on the tab to tell different stories

#this is where the main graph is created. first by creating a new dataframe where a new column is created that shows the total bat calls per year by species, while filtering out all noise.
bats.per <- bats %>% 
  filter(! grepl('Noise', AUTO.ID, ignore.case = TRUE)) %>% 
  group_by(year) %>% 
  mutate(tot_bat = n())

# the vision was to have percentages that are displayed on the graph, so essentially the proportion of species bat recordings are put over total recordings, then multiplied by 100 to give a percent, with the distinction of a percentage being taken from each year as well.

bats.per <- bats.per %>% 
  mutate(year = factor(year, levels = min(bats.per$year):max(bats.per$year))) %>% 
  group_by(year, AUTO.ID, Common) %>% 
  summarise(prop = n()/tot_bat, 
            perc = prop*100)


# using the distinct command so there is only one observation per species per year
bats.per <- distinct(bats.per)

#this is a custom colorblind palette because all others only contain 8
cbPalette <- c("#600047", "#d7a8d4", "#f5dfef", "#fe5f00","#fed457", "#c2c527", "#9ae825","#6f9c01", "#c5d5ea","#d3ffe2",  "#a2c2c6", "#087d93","#0c3660", "#9200bc")

# the ggplot graph was made first, plotting the percentages of each species against the different years, which each species representing a color on the bars. This is all wrapped inside of an object so that plotly can be used. The text = paste function dictates what text goes inside of the box of text from the hover over feature. 
diversity_graph <- ggplot(data = bats.per)+
  geom_col(aes(x = year,
               y = perc,
               fill = AUTO.ID, 
               text = paste("Percentage:",round(prop*100, 1),
                            "Species:", Common)))+
  scale_fill_manual(values = cbPalette)+
  labs(title = 'Diversity Trends of Bat Species',
       subtitle = 'Percentages of Every Year since 2017',
       x = 'Year',
       y = 'Percent of Total Recordings')
  

# this is the plotly object, with tooltip serving as instructions for what the hover textbox looks like.
ggplotly(diversity_graph, tooltip = c("fill", "text"))

```




Exploratory Analysis


# trying to learn plotly

# commented this out as the one below is better but i might need this if i mess it up too far
```{r}

# essentially this was all of the code repeated a second time before plotly was integrated in case of a dire circumstance. 

# bats.per <- bats %>% 
 # filter(! grepl('Noise', AUTO.ID, ignore.case = TRUE)) %>% 
#  group_by(year, COMPARTMENT) %>% 
 # mutate(tot_bat = n())

#bats.per <- bats.per %>% 
 # group_by(year, AUTO.ID, COMPARTMENT) %>% 
 # summarise(prop = n()/tot_bat, 
  #          perc = prop*100)

# bats.per <- distinct(bats.per)


# diversity_graph <- ggplot(data = bats.per)+
 # geom_col(aes(x = year,
   #            y = perc,
     #          fill = AUTO.ID, 
    #           text = paste("Compartment:", COMPARTMENT,
             #               "Percentage:", prop*100)))


# ggplotly(diversity_graph, tooltip = c("fill", "text"))
``` 

The following pieces of code are not included on the dashboard, but were a part of the exploratory analysis that aided in our understanding of the data. 

```{r}
# account for number of sensors active on each date -----
bats.daily <- bats %>%
  group_by(DATE) %>%
  mutate( nSensors = length(unique(sensor)) )
bats.daily <- bats.daily %>%
  filter(! AUTO.ID %in% No.ID) %>%
  group_by(DATE,AUTO.ID) %>%
  summarize( count = n(),
             relFreq = count/nSensors )
bats.daily <- distinct(bats.daily)
chosen_species <- levels(factor(bats.daily$AUTO.ID))
# wanting to graph just to see what they all look like over time
ggplot(data = bats.daily %>% filter(AUTO.ID %in% chosen_species)) +
         geom_line(aes( x = DATE,
                 y = count,
                 color = AUTO.ID,
                 alpha = 0.7))
# now i would like to look at just MYOTIS species
ggplot(data = bats.daily %>% filter(AUTO.ID == 'MYOLUC'))+
  geom_line(aes(x = DATE,
                 y = count),
            color = 'blue') +
  labs(title = 'Little Brown Bat Frequencies',
       subtitle = 'Across all Available Years',
       x = 'Year',
       y = 'Frequency')
```

```{r}
# my goal here is to try and understand trends between EPTFUS and MYOLUC, maybe a cute lil facet wrap for sensors so that I can see if any of them are/were in the same place. anyways

big_v_lil <- bats %>% 
  group_by(AUTO.ID, sensor, DATE) %>% 
  filter(AUTO.ID %in% c('MYOLUC','EPTFUS')) %>% 
  tally()

ggplot(data = big_v_lil)+
  geom_line(aes(x = DATE,
                y = n,
                color = AUTO.ID))+
  labs(title = 'EPTFUS vs. MYOLUC Presence',
       x = 'Date',
       y = 'Number of Recordings')+
  facet_wrap(~sensor)

# taking a closer look at one of the censors with a lot of activity
ggplot(data = big_v_lil %>% filter(sensor == "C22_S9"))+
  geom_line(aes(x = DATE,
                y = n,
                color = AUTO.ID))+
  labs(title = 'EPTFUS vs. MYOLUC Presence',
       x = 'Date',
       y = 'Number of Recordings')

# i would love if we put this on the dashboard, if you could choose which sensor graph youre looking at
```


```{r}
# this is an early draft of the main diversity graph.
bats.prop <- bats %>% 
  filter(! grepl('Noise', AUTO.ID, ignore.case = TRUE)) %>% 
  group_by(year) %>% 
  mutate(tot_bat = n())

bats.prop <- bats.prop %>% 
  group_by(year, AUTO.ID) %>% 
  summarise(prop = n()/tot_bat, 
            perc = prop*10)

bats.prop <- distinct(bats.prop)
  
 ggplot(data = bats.prop)+
   geom_line(aes(x = year,
                 y = prop,
                 color = AUTO.ID))
```





# DASHBOARD PREP

```{r}
# Universal inputs (grouping, group, year, month)
# diversity.wrapVar (vector - none, management)
bad <- c('no.ID','Noise')

# stand-in input variables -----
input.grouping <- 'species group'
input.group <- unique(bats$species_group)
input.group <- input.group[-which(input.group%in%bad)]
input.year <- c(2017:2022)
input.month <- month.abb[1:12]
diversity.wrapVar <- 'none'

# colorblind palatte -----
cbPalette <- c("#600047", "#d7a8d4", "#f5dfef", "#fe5f00","#fed457", "#c2c527", "#9ae825","#6f9c01", "#c5d5ea","#d3ffe2",  "#a2c2c6", "#087d93","#0c3660", "#133139")
```

```{r}
# basic filter -----
bats.sub <- bats %>% 
  filter( year %in% input.year, month %in% input.month )

# set grouping var column -----
if(input.grouping=='species'){ bats.sub <- bats.sub %>% mutate(group=AUTO.ID) }
if(input.grouping=='species group'){ bats.sub<-bats.sub%>%mutate(group=species_group) }
if(input.grouping=='cave dependency'){ bats.sub <- bats.sub %>% mutate(group=obligate) }

# group filter -----
bats.sub <- bats.sub %>% 
  filter( group %in% input.group )
```

```{r}
# set wrap var column -----
if(diversity.wrapVar=='management'){ bats.div <- bats.sub %>% mutate(wrapV=habitat) }

# summarize by appropriate groups -----
if(diversity.wrapVar=='none'){
  bats.div <- bats.sub %>% 
    group_by(year) %>% 
    mutate( total=n() )
  bats.div <- bats.div %>% 
    mutate( year=factor(year, levels=min(year):max(year)) ) %>% 
    group_by(year,group,group_common) %>% 
    summarise( prop = n()/total, 
               perc = prop*100 )
} else {
  bats.div <- bats.div %>% 
    group_by(year,wrapV) %>% 
    mutate( total=n() )
  bats.div <- bats.div %>% 
    mutate( year=factor(year, levels=min(year):max(year)) ) %>% 
    group_by(year,wrapV,group,group_common) %>% 
    summarise( prop = n()/total, 
               perc = prop*100 )
}
bats.div <- distinct(bats.div)
```

```{r}
# make base plot -----
diversity.p <- ggplot( bats.div ) +
  geom_col( aes( x=year, y=perc, fill=group_common, 
                 text=paste0("Percentage: ",round(perc),"% ") ) )+
  scale_fill_manual(values = cbPalette)+
  labs(title='Bat Species Proportions',
       x='Year', y='Percent of Total Activity',
       caption="Sewanee Bat Study, DataLab 2022",
       fill="Species Group")
  
# wrap if appropriate -----
if(diversity.wrapVar != 'none'){
  diversity.p <- diversity.p + facet_wrap(~wrapV)
}

# plot with plotly -----
#ggplotly(diversity.p, tooltip=c("fill", "perc", "spec"))
diversity.p
```










