---
title: 'Bats: Circadian Trends'
author: "Hallie Rutten, Shelby Cline, Monae Scott"
date: '2022-06-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# basic read -----
source('dataRead-bats.R')
bats <- bats %>% 
  rename( siteID = sensor) %>% 
  select(-LATITUDE,-LONGITUDE)

# sensor data read -----
source('dataRead-sensorDates.R')
  
# join bats and sensor site data -----
bats <- left_join(bats,sensorDates, by=c('siteID','DATE'))
```





# EXPLORATORY:

## Circadian (hourly) Trends

Bat activity by hour of day

### Hourly

```{r}
# account for number of sensors active in each hour -----
bats.hourly <- bats %>% 
  group_by(hour) %>% 
  mutate( nSensors = length(unique(siteID)) )

bats.hourly <- bats.hourly %>% 
  group_by(hour,AUTO.ID) %>% 
  summarize( count = n(), 
             relFreq = count/nSensors )

bats.hourly <- distinct(bats.hourly)%>% 
  filter(!grepl('NoID',AUTO.ID,ignore.case=TRUE))
```

```{r}
# graph hourly bat activity -----
ggplot( bats.hourly ) +
  geom_line( aes(x=hour, y=relFreq, color=AUTO.ID) ) +
  labs(title="Hourly Bat Activity",
       x="Hour of Day", y="Relative Frequency", 
       caption="DataLab 2022",
       color="Species")
```

### Hour and Month

```{r}
# account for number of sensors active in each month-hour -----
bats.hr.mon <- bats %>% 
  group_by(hour,month) %>% 
  mutate( nSensors = length(unique(siteID)) )

bats.hr.mon <- bats.hr.mon %>% 
  group_by(hour,month,AUTO.ID) %>% 
  summarize( count = n(), 
             relFreq = count/nSensors )

bats.hr.mon <- distinct(bats.hr.mon) %>% 
  filter(!grepl('NoID',AUTO.ID,ignore.case=TRUE)) %>% 
  mutate( month = factor(month, levels=month.abb[1:12]) )
```

```{r}
# graph hourly bat activity by month -----
ggplot( bats.hr.mon ) +
  geom_line( aes(x=hour, y=relFreq, color=AUTO.ID) ) +
  facet_wrap(~month) +
  labs(title="Hourly Bat Activity",
       x="Hour of Day", y="Relative Frequency", 
       caption="DataLab 2022",
       color="Species")
```

### Hour and Year

```{r}
# account for number of sensors active in each year-hour -----
bats.hr.yr <- bats %>% 
  group_by(hour,year) %>% 
  mutate( nSensors = length(unique(siteID)) )

bats.hr.yr <- bats.hr.yr %>% 
  group_by(hour,year,AUTO.ID) %>% 
  summarize( count = n(), 
             relFreq = count/nSensors )

bats.hr.yr <- distinct(bats.hr.yr)%>% 
  filter(!grepl('NoID',AUTO.ID,ignore.case=TRUE))
```

```{r}
# graph hourly bat activity by year -----
ggplot( bats.hr.yr ) +
  geom_line( aes(x=hour, y=relFreq, color=AUTO.ID) ) +
  facet_wrap(~year, ncol=3) +
  labs(title="Hourly Bat Activity",
       x="Hour of Day", y="Relative Frequency", 
       caption="DataLab 2022",
       color="Species")
```





# DASHBOARD PREP:

## Circadian Trends

```{r}
# set stand-in input vars -----

#use unique() to use all years, others for specific or single years
  selectedYears <- unique(bats$year)
  #selectedYears <- c(2020,2021)
  #selectedYears <- 2019

#use unique() to use all compartments, others for specific or single compartments
  selectedComps <- unique(bats$COMPARTMENT)
  #selectedComps <- c("C20","C22","C33")
  #selectedComps <- "C50"
  
#use unique() to show all species, others for specific or single species
  #selectedSpecies <- unique(bats$AUTO.ID)
  selectedSpecies <- c("CORRAF","EPTFUS","LASBOR")
  #selectedSpecies <- "NYCHUM"

#use whichever is selected (single input choice)
  wrapVar <- 'year'
  #wrapVar <- 'month'
  #wrapVar <- 'habitat'
  #wrapVar <- 'none'
```

```{r}
# filter data by stand-in input vars -----
bats.sub <- bats %>% 
  filter( year %in% selectedYears, 
          COMPARTMENT %in% selectedComps,
          AUTO.ID %in% selectedSpecies,
          !grepl('NoID',AUTO.ID,ignore.case=TRUE) )

if(wrapVar == 'year'){
  bats.sub <- bats.sub %>% 
    group_by(hour, year) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,year,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
if(wrapVar == 'month') {
  bats.sub <- bats.sub %>% 
    group_by(hour, month) %>% 
    mutate( nSensors = length(unique(siteID)),
            month = factor(month, levels=month.abb[1:12]) )
  bats.sub <- bats.sub %>% 
    group_by(hour,month,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
if(wrapVar == 'habitat'){
  bats.sub <- bats.sub %>% 
    group_by(hour, habitat) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,habitat,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
if(wrapVar == 'none'){
  bats.sub <- bats.sub %>% 
    group_by(hour) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
bats.sub <- distinct(bats.sub)
```

```{r}
# graph with stand-in input vars -----
circadian.plot <- ggplot( bats.sub ) +
  geom_line( aes(x=hour, y=relFreq, color=AUTO.ID) )

if(wrapVar == 'year'){
  circadian.plot + facet_wrap(~year)
}
if(wrapVar == 'month'){
  circadian.plot + facet_wrap(~month)
}
if(wrapVar == 'habitat'){
  circadian.plot + facet_wrap(~habitat)
}
if(wrapVar == 'none'){
  circadian.plot
}
```




# DASHBOARD PREP ROUND 2:

## Circadian Trends

```{r}
# set stand-in input vars -----

#use unique() to use all years, others for specific or single years
  selectedYears <- unique(bats$year)
  #selectedYears <- c(2020,2021)
  #selectedYears <- 2019

#use unique() to use all compartments, others for specific or single compartments
  selectedComps <- unique(bats$COMPARTMENT)
  #selectedComps <- c("C20","C22","C33")
  #selectedComps <- "C50"
  
#use unique() to show all species, others for specific or single species
  #selectedSpecies <- unique(bats$AUTO.ID)
  selectedSpecies <- c("CORRAF","EPTFUS","LASBOR")
  #selectedSpecies <- "NYCHUM"

#use whichever is selected (single input choice)
  wrapVar <- 'year'
  #wrapVar <- 'month'
  #wrapVar <- 'habitat'
  #wrapVar <- 'none'
```

```{r}
# filter data by stand-in input vars -----
bats.sub <- bats %>% 
  filter( year %in% selectedYears, 
          COMPARTMENT %in% selectedComps,
          AUTO.ID %in% selectedSpecies )

if(wrapVar == 'year'){ bats.sub <- bats.sub %>% mutate(wrapV = year) }
if(wrapVar == 'month'){ bats.sub <- bats.sub %>% mutate(wrapV = month) }
if(wrapVar == 'habitat'){ bats.sub <- bats.sub %>% mutate(wrapV = habitat) }

if(wrapVar == 'none'){
  bats.sub <- bats.sub %>% 
    group_by(hour) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
} else {
  bats.sub <- bats.sub %>% 
    group_by(hour, wrapV) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,wrapV,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
```

```{r}
# graph with stand-in input vars -----
circadian.plot <- ggplot( bats.sub ) +
  geom_line( aes(x=hour, y=relFreq, color=AUTO.ID) )

if(wrapVar == 'none'){
  circadian.plot
} else {
  circadian.plot + facet_wrap(~wrapV)
}
```


