---
title: "Bats: Long-Term Trends"
author: "Shelby Cline, Hallie Rutten, Monae Scott"
date: '2022-06-27'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# basic read -----
source('dataRead.R')
bats <- bats %>%  
  rename( siteID = sensor) %>% 
  select(-LATITUDE,-LONGITUDE)

# sensor data read -----
source('dataRead-sensorDates.R')
  
# join bats and sensor site data -----
bats <- left_join(bats,sensorDates, by=c('siteID','DATE'))

No.ID = c("Noise", "NoId", "NoID")
```

# Long-Term (yearly) and Climate (temperature/weather) Trends

This is the main graph


```{r}
# want to create a column of cave obligates versus non-cave obligates to observe their activity

#take the total number of non cave bats divided by the number of cave dwelling bats in the whole year 
cave_obligate = c('PERSUB', 'MYOLEI', 'MYOAUS', 'MYOLUC', 'MYOSOD', 'MYOGRI', 'MYOSEP')
non_cave_obligate = c('LASBOR', 'NYCHUM', 'EPTFUS', 'LASNOC', 'LASCIN', 'CORRAF')
cave_ob <- bats %>%
  mutate(`cave obligate?` = AUTO.ID %in% cave_obligate) %>%
  filter(! AUTO.ID %in% No.ID) %>% 
  group_by(year, `cave obligate?`) %>% 
  mutate(tot_bat = n()) 
```

```{r}
# to make this graph as accurate as possible, we put the proportion of CO bats in december over total NCO bats over time, and then vice versa to graph
cave_ob <- cave_ob %>% 
  group_by(monthN, `cave obligate?`, year) %>%
  summarize(prop_bat = n()/tot_bat) %>% 
  filter(monthN == 12)

ggplot(data = cave_ob,
       aes(x = year,
           y = prop_bat,
           color = `cave obligate?`))+
  geom_line()+
  labs(title = "Bat Activity in All Recorded Decembers",
       subtitle = "With Cave Obligate Bats vs. Non-Cave Obligate Bats, 
Weighted by Proportion to Total Recordings",
       x = "Year",
       y = "Bat Activity")
# theres a sharp dip in frequencies of both bats in 2020. interesting.
```

Looking into making species group columns

```{r}
EPTFUS.LASNOC = c("EPTFUS", "LASNOC")
LASBOR.NYCHUM = c('LASBOR', "NYCHUM")
bats <- bats %>% 
  mutate(species_group = ifelse(grepl("^MYO", AUTO.ID), "MYOTIS", AUTO.ID),
         species_group = ifelse(AUTO.ID %in% EPTFUS.LASNOC, "EPTFUS.LASNOC", species_group),
         species_group = ifelse(AUTO.ID %in% LASBOR.NYCHUM, "LASBOR.NYCHUM", species_group))

cave_obligate = c('PERSUB', 'MYOLEI', 'MYOAUS', 'MYOLUC', 'MYOSOD', 'MYOGRI', 'MYOSEP')
non_cave_obligate = c('LASBOR', 'NYCHUM', 'EPTFUS', 'LASNOC', 'LASCIN', 'CORRAF')
bats <- bats %>%
  mutate(`cave obligate?` = ifelse(AUTO.ID %in% cave_obligate, TRUE, NA),
         `cave obligate?` = ifelse(AUTO.ID %in% non_cave_obligate, FALSE, `cave obligate?`))
  
```


```{r}
# Possible input values
selectedGroup <- 'species' # species_group or by cave_ob
selectedSpecies <- c("CORRAF","EPTFUS","LASBOR")

selectedGroup <- 'species_group'
selectedSpecies <- c('EPTFUS.LASNOC')

selectedGroup <- 'cave obligate?'
selectedSpecies <- 'FALSE'

#use unique() to use all years, others for specific or single years
  selectedYears <- unique(bats$year)
  #selectedYears <- c(2020,2021)
  #selectedYears <- 2019

#use whichever is selected (single input choice)
  wrapVar <- 'year'
  #wrapVar <- 'month'
  #wrapVar <- 'habitat'
  #wrapVar <- 'none'
```


```{r}
# species call counts by year -----



# Filter based on inputs
bats.sub <- bats %>% 
  filter( year %in% selectedYears, 
          !grepl('NoID',AUTO.ID,ignore.case=TRUE) )


# Now prep by selected group
if(selectedGroup == 'species'){ bats.sub <- bats.sub %>% mutate(groupby = AUTO.ID) }
if(selectedGroup == 'species_group'){ bats.sub <- bats.sub %>% mutate(groupby = species_group) }
if(selectedGroup == 'cave obligate?'){ bats.sub <- bats.sub %>% mutate(groupby = `cave obligate?`) }

bats.sub <- bats.sub %>% 
  filter(groupby %in% selectedSpecies)

# first, we created a dataframe to manipulate
# then we filter out any no.id data and any noise data. also, the year 2022 is excluded as its incomplete
# the mutate nsensors is so that we can account for survey effort
bats.time <- bats.sub %>%
  filter(! AUTO.ID %in% No.ID, year < 2022) %>%
  group_by(year) %>%
  mutate(nsensors = length(unique(siteID))) 

# another code segment to utilize another group_by, this time so i can see the relative frequency of the species per year
bats.time <- bats.time %>% 
  group_by(year, groupby) %>% 
  summarize(count = n(),
            rel_freq = count/nsensors)

bats.time <- unique(bats.time)

#this is just the plot, its copied almost exactly below so we could put it inside of an object to be used in the ggplotly function.
ggplot(data=bats.time,
       aes(x=year,
           y=rel_freq,
           color=groupby) )+
  geom_line()+
  labs(title = 'Number of Total Calls Per Species',
       subtitle = "From 2017-2021",
       x = 'Year', y = 'Number of Calls')

longterm_graph <- ggplot(data=bats.time, 
                         aes(x=year,
                             y=rel_freq, 
                             color=groupby) )+
  geom_line()+
  labs(title = 'Number of Total Calls Per Species',
       subtitle = "From 2017-2021",
       x = 'Year', y = 'Number of Calls')

# using hovertemplate allows us to zoom into the graph

ggplotly(longterm_graph, hovertemplate = paste())


# ok im going to try and format this for the dashbaord
```


This is experimental stuff


```{r}
# my goal is to group everything and then use summarize so that I can have the total frequency of the bats by species across months.
freq_by_month <- bats %>%
  group_by(year, monthN, AUTO.ID) %>%
  filter(! AUTO.ID %in% No.ID) %>%
  summarize(frequencies = n())
# With the graph, I want to filter to keep only specific year and species combinations for clarity, and I want months to be on the x-axis and the number of calls recorded on the y.
chosen_species <- levels(factor(freq_by_month$AUTO.ID))
ggplot(data = freq_by_month %>% filter(AUTO.ID %in% chosen_species, year == 2017),
       aes(x = monthN,
           y = frequencies,
           color = AUTO.ID))+
  geom_line()+
  labs(title = 'Frequencies by Month',
       subtitle = 'During 2017',
       x = 'Month by Number',
       y = 'Number of Calls')
  
# here i just wanted to look at the total number of recordings across all species

bats %>%
  group_by(AUTO.ID) %>%
  tally()
```

```{r}
# account for number of sensors active on each date -----
bats.daily <- bats %>%
  group_by(DATE) %>%
  mutate( nSensors = length(unique(siteID)) )
bats.daily <- bats.daily %>%
   filter(! AUTO.ID %in% No.ID) %>%
  group_by(DATE,AUTO.ID) %>%
  summarize( count = n(),
             relFreq = count/nSensors )
bats.daily <- distinct(bats.daily)
chosen_species <- levels(factor(bats.daily$AUTO.ID))
# wanting to graph just to see what they all look like over time
ggplot(data = bats.daily %>% filter(AUTO.ID %in% chosen_species)) +
         geom_line(aes( x = DATE,
                 y = count,
                 color = AUTO.ID,
                 alpha = 0.7))
# now i would like to look at just MYOTIS species
ggplot(data = bats.daily %>% filter(AUTO.ID == 'MYOLUC'))+
  geom_line(aes(x = DATE,
                 y = count),
            color = 'blue') +
  labs(title = 'Little Brown Bat Frequencies',
       subtitle = 'Across all Available Years',
       x = 'Year',
       y = 'Frequency')
```

```{r}
# the goal here was to create a data frame containing the amount of frequencies recorded of a specific species at a specific sensor
selected_year <- 2017
bats.ym <- bats %>%
  group_by(year, month, AUTO.ID, siteID) %>%
  tally()
# then we graphed it and facet-wrapped by sensor to look into each individual one with available data
ggplot(data = bats.ym %>% filter(year == selected_year),
       aes(x = month,
           y = n,
          fill = AUTO.ID))+
  geom_col(position = "dodge")+
  facet_wrap(~siteID)
```




```{r}
# simple graph of overall amount of recorded calls to start the day

 overall_bats <- bats %>%
 group_by(AUTO.ID) %>%
  tally()


# this is an actual plot for the overall calls
ggplot(data = overall_bats)+
  geom_col(aes(x = AUTO.ID,
               y = n))+
  labs(title = 'Total Recordings by Species',
       x = 'Species',
       y = 'Number of Calls')+
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))+
  scale_y_continuous(labels = comma)

```

```{r}
# my goal here is to try and understand trends between EPTFUS and MYOLUC, maybe a cute lil facet wrap for sensors so that I can see if any of them are/were in the same place. anyways

big_v_lil <- bats %>% 
  group_by(AUTO.ID, siteID, DATE) %>% 
  filter(AUTO.ID %in% c('MYOLUC','EPTFUS')) %>% 
  tally()

ggplot(data = big_v_lil)+
  geom_line(aes(x = DATE,
                y = n,
                color = AUTO.ID))+
  labs(title = 'EPTFUS vs. MYOLUC Presence',
       x = 'Date',
       y = 'Number of Recordings')+
  facet_wrap(~siteID)

# taking a closer look at one of the censors with a lot of activity
ggplot(data = big_v_lil %>% filter(siteID == "C22_S9"))+
  geom_line(aes(x = DATE,
                y = n,
                color = AUTO.ID))+
  labs(title = 'EPTFUS vs. MYOLUC Presence',
       x = 'Date',
       y = 'Number of Recordings')

# i would love if we put this on the dashboard, if you could choose which sensor graph youre looking at

```



```{r}

# How have the MYOTIS species fluctuated over time?

myotis <- bats %>% 
  group_by(AUTO.ID, siteID, DATE, monthN) %>% 
  filter(AUTO.ID %in% c("MYOLUC","MYOLEI", "MYOSOD", "MYOAUS", "MYOSEP", "MYOGRI")) %>% 
  tally()

ggplot(data = myotis)+
  geom_line(aes(x = DATE,
                y = n,
                color = AUTO.ID))+
  labs(title = 'MYOTIS Species Over Time',
       x = 'Time',
       y = 'Number of Recordings')+
  facet_wrap(~AUTO.ID)


```

```{r}

selectedYears <- unique(bats$year)
selectedComps <- unique(bats$COMPARTMENT)
selectedSpecies <- unique(bats$AUTO.ID)

 wrapVar <- 'year'
  #wrapVar <- 'month'
  #wrapVar <- 'habitat'
  #wrapVar <- 'none'
 
 
 
bats.sub <- bats %>% 
  filter( year %in% selectedYears, 
          COMPARTMENT %in% selectedComps,
          AUTO.ID %in% selectedSpecies,
          !grepl('NoID',AUTO.ID,ignore.case=TRUE) )

if(wrapVar == 'year'){
  bats.sub <- bats.sub %>% 
    group_by(hour, year) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,year,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
if(wrapVar == 'month') {
  bats.sub <- bats.sub %>% 
    group_by(hour, month) %>% 
    mutate( nSensors = length(unique(siteID)),
            month = factor(month, levels=month.abb[1:12]) )
  bats.sub <- bats.sub %>% 
    group_by(hour,month,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
if(wrapVar == 'habitat'){
  bats.sub <- bats.sub %>% 
    group_by(hour, habitat) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,habitat,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
if(wrapVar == 'none'){
  bats.sub <- bats.sub %>% 
    group_by(hour) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.sub <- bats.sub %>% 
    group_by(hour,AUTO.ID) %>% 
    summarize( count = n(), relFreq = count/nSensors )
}
bats.sub <- distinct(bats.sub)




```
