---
title: 'Bats: Seasonal Trends'
author: "Hallie Rutten, Shelby Cline, Monae Scott"
date: '2022-06-29'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(plotly)

source('dataRead-bats.R')

bats <- bats %>% 
  filter(! AUTO.ID %in% c("NoId","NoID","no.ID","Noise") )
```

# Seasonal (monthly) Trends

```{r}
library(readxl)
#read in daily weather data
weather <- read_xlsx("SUD Weather Station.xlsx")

#read in hourly weather data
hourly<-read_xlsx("SUD Weather Station.xlsx", sheet=2)

#read in recorded rain data
rain<-read_xlsx("SUD Weather Station.xlsx", sheet = 3)

```

```{r}
#rename column names in weather df
colnames(weather)
weather <- weather %>%
  dplyr::rename("Date" = "Timestamp*",
         AvgTemp='Air temp Avg (C)',
         Highest_Temp_Time='Time Air Temp Max',
         MaxTemp='Air Temp Max (C)',
         MinTemp='Air Temp Min',
         MaxWind='Wind Speed Max (low) (m/s)',
         AvgWind='Wind Speed Avg (high) (m/S)',
         MinWind='Wind Speed Min (low) (m/s)')


#Create 'Date' variable 
hourly<-hourly %>% 
  mutate(Date= date(Timestamp)) 

#create 'rainfall' variable to get the avg. rainfall per recorded day 
daily_rainfall<-hourly %>%  
  mutate(Month= month(Timestamp)) %>% 
  mutate(Year= year(Timestamp)) %>% 
  group_by(Year, Date, Month) %>% 
  summarise(total_rainfall = sum(`Rain (mm)`),
            total_hours = n()) %>% 
  mutate(mm_hr = total_rainfall / total_hours) %>% 
  mutate(mm_predicted = mm_hr * 24) 


#get the rainfall for the year
yearly_rainfall <- daily_rainfall  %>% 
  drop_na( Year ) %>% 
  group_by(Year) %>%
  summarise(rain_intensity= sum(total_rainfall)/sum(total_hours)) 
View(yearly_rainfall)  

#ignoring 2017 and NA bc it wasn't enough data
monthly_rainfall<-daily_rainfall %>%  
  group_by(Month,Year) %>% 
  summarise(rain_intensity= sum(total_rainfall)/sum(total_hours)) 
View(monthly_rainfall)

#create 'month' and 'year' column
#create 'df' 
df <- bats %>% 
  mutate(Month= month(DATE)) %>% 
  mutate(Year= year(DATE)) %>% 
  group_by(Month, Year, AUTO.ID) %>% 
  tally() %>%
  ungroup()

#combine 'df' and 'monthly_rainfall' to create plot 
df <- left_join(df, monthly_rainfall, by=c('Month', 'Year'))
 
###filter out 2017 because there isn't enough data to show anything significant
df<-df %>% 
  filter(Year>2017) 

###filter out 2017 and 2022 because there isn't enough data to show anything significant
monthly_rainfall<-monthly_rainfall%>% 
  filter(Year>2017,Year<2022) 
#plot monthly rainfall 
#name plot 'm_rainfall' to graph it using plotly
m_rainfall<-ggplot(data = monthly_rainfall, aes(x=Month, y=rain_intensity, fill=Year))+
  geom_area()+
  labs(title='Monthly Rainfall by Year', caption = 'Sewanee Bat Study. DataLab 2022', y='Total Rain Intensity (mm/hr)')+
  facet_wrap(~Year)+
   theme( legend.position = "none" ) +
  scale_x_continuous(breaks = 1:12)

ggplotly(m_rainfall, hovertemplate = paste())  
```

```{r}
library(ggplot2)
#create Year and Month variable from Date column
df <- df %>% 
  mutate( Date = ymd(paste0( Year, "-", Month, "-1") ) )
view(df)
#filter out 2017 and 2022; not enough data
df<-df%>% 
  filter(Year>2017, Year<2022)

```

```{r}
#convert temp.from Celsius to Fahrenheit#
#Max temp
Fahrenheit<-weather %>% 
  mutate(MaxTemp_f = MaxTemp*(9/5)+32)

#Min temp
Fahrenheit<-Fahrenheit %>% 
  mutate(MinTemp_f = MinTemp*(9/5)+32)

#Average temp
Fahrenheit<-Fahrenheit %>% 
  mutate(AvgTemp_f = AvgTemp*(9/5)+32)

#merge df and fahrenheit
#first need to create a month and year column in Fahrenheit data set

Fahrenheit<-Fahrenheit %>% 
  mutate(Month= month(Date)) %>% 
  mutate(Year= year(Date))


#Get the mean of min, max, and average temp to plot better.
df.2<-Fahrenheit %>%  
  group_by(Month, Year) %>% 
  summarise(AvgTemp_f = mean(`AvgTemp_f`),
            MaxTemp_f = mean(`MaxTemp_f`),
            MinTemp_f = mean(`MinTemp_f`))

drop_na(df.2)
###filter out 2017 and 2022 because there isn't enough data to show anything significant
df.2<-df.2%>% 
  filter(Year>2017, Year<2022)
#plot max, min, avg temp 
#name plot 'temps' to graph it using plotly
temps<-ggplot(data = df.2, aes(x=Month, ymin=MinTemp_f, ymax=MaxTemp_f, y=AvgTemp_f))+
  geom_ribbon(fill = "lightpink")+
  geom_line(color="red")+
  labs(title = 'Temperature ', subtitle = 'Maximum, Minimum, and Average', caption = 'Sewanee Bat Study. DataLab 2022', y='Temperature (째F)')+
  facet_wrap(~Year)+
  scale_x_continuous(breaks = 1:12)
  
ggplotly(temps, hovertemplate = paste())   

```

```{r}
#wind monthly for each year
windy<-weather %>% 
  mutate(Month= month(Date)) %>% 
  mutate(Year= year(Date))

#mean of wind ?intensity? 
df.3<-windy %>%  
  group_by(Month, Year) %>% 
  summarise(AvgWind = mean(`AvgWind`),
            MaxWind = mean(`MaxWind`),
            MinWind = mean(`MinWind`))

drop_na(df.3)

df.3<-df.3%>% 
  filter(Year>2017, Year<2022) 

#plot wind intensity? 
#name plot 'w_intensity' to graph it using plotly
w_intensity<-ggplot(data = df.3, aes(x=Month, ymin=MinWind, ymax=MaxWind, y=AvgWind))+
  geom_ribbon(fill = "gray")+
  geom_line(color="darkgray")+
  labs(title='Monthly Wind Intensity', subtitle = 'By year', caption= 'Sewanee Bat Study. DataLab 2022',y='Total Wind Speed (m/s)')+
  facet_wrap(~Year)+
   theme( legend.position = "none" ) +
  scale_x_continuous(breaks = 1:12)

ggplotly(w_intensity, hovertemplate = paste()) 

```

```{r}
#overall temp. trends across the years on one graph
#just the average
library(plotly)
#mean of temp
yearly_rainfall<-yearly_rainfall%>% 
  filter(Year>2017, Year<2022)

#name plot 'temp_graph' to graph it using plotly
temp_graph<-ggplot(data=df.2, aes(x=Month, y=AvgTemp_f, group=Year, color=Year))+
  geom_line()+
  labs(title = 'Overall Averages for Temperature ', caption = 'Sewanee Bat Study. DataLab 2022', y='Temperature (째F)')+
  scale_x_continuous(breaks = 1:12)

ggplotly(temp_graph, hovertemplate = paste())  
```

```{r}
source('dataRead-bats.R')
library(readxl)
batspecies <- read_excel("BatSpecies.xlsx")

bats <- bats %>%  
  rename( siteID = sensor) %>% 
  select(-LATITUDE,-LONGITUDE)
# sensor data read -----
source('dataRead-sensorDates.R')
  
# join bats and sensor site data -----
bats <- left_join(bats,sensorDates, by=c('siteID','DATE'))
No.ID = c("Noise", "NoId", "NoID")  


bats<-left_join(bats,batspecies, by="AUTO.ID")
###
bats.time <- bats %>%
  filter(! AUTO.ID %in% No.ID, year < 2022) %>%
  group_by(year) %>%
  mutate(nsensors = length(unique(siteID)))
# another code segment to utilize another group_by, this time so i can see the relative frequency of the species per year
bats.time <- bats.time %>% 
  group_by(monthN, year, AUTO.ID) %>% 
  summarize(count = n(),
            rel_freq = count/nsensors)
bats.time <- unique(bats.time)


###filter out 2017 and 2022 because there isn't enough data to show anything significant
bats.time<-bats.time%>% 
  filter(year>2017, year<2022)

#name plot 'bats.time.2' to graph it using plotly
bats.time.2<-ggplot(data=bats.time,
       aes(x=monthN,
           y=rel_freq,
           color=AUTO.ID) )+
  geom_line()+
  facet_wrap(~year)+
  labs(title = 'Number of Total Calls Per Species',
       subtitle = "From 2017-2021",
       x = 'Year', y = 'Number of Calls')+
    scale_x_continuous(breaks = 1:12)

#Using plotly to create a hover function
ggplotly(bats.time.2, hovertemplate = paste())  

```

```{r}

# ####graphs for dashboard####
# output$monthly.plot <- renderPlot({
#     ggplot() +
#       labs(title="Seasonal Bat Activity",
#            x="Month", y="Relative Frequency",
#            caption="Sewanee Bat Study, DataLab 2022")
#  
# })
# 
# #rain plot
# m_rainfall<-ggplot(data = monthly_rainfall, aes(x=Month, y=rain_intensity, fill=Year))+
#   geom_area()+
#   labs(title='Monthly Rainfall by Year', caption = 'Sewanee Bat Study. DataLab 2022', y='Total Rain Intensity (mm/hr)')+
#   facet_wrap(~Year)+
#    theme( legend.position = "none" ) +
#   scale_x_continuous(breaks = 1:12)
# 
# #Using plotly to create a hover function
# ggplotly(m_rainfall, hovertemplate = paste())  
# 
# 
# #wind plot
# 
# w_intensity<-ggplot(data = df.3, aes(x=Month, ymin=MinWind, ymax=MaxWind, y=AvgWind))+
#   geom_ribbon(fill = "gray")+
#   geom_line(color="darkgray")+
#   labs(title='Monthly Wind Intensity', subtitle = 'By year', caption= 'Sewanee Bat Study. DataLab 2022',y='Total Wind Speed (m/s)')+
#   facet_wrap(~Year)+
#    theme( legend.position = "none" ) +
#   scale_x_continuous(breaks = 1:12)
# 
# #Using plotly to create a hover function
# ggplotly(w_intensity, hovertemplate = paste())
# 
# ########Temp. plots#####
# ##Plot Max, Min, Avg temperature 
# 
# temps<-ggplot(data = df.2, aes(x=Month, ymin=MinTemp_f, ymax=MaxTemp_f, y=AvgTemp_f))+
#   geom_ribbon(fill = "lightpink")+
#   geom_line(color="red")+
#   labs(title = 'Temperature ', subtitle = 'Maximum, Minimum, and Average', caption = 'Sewanee Bat Study. DataLab 2022', y='Temperature (째F)')+
#   facet_wrap(~Year)+
#   scale_x_continuous(breaks = 1:12)
# 
# #Using plotly to create a hover function  
# ggplotly(temps, hovertemplate = paste())   
# 
# ###Species 2018-2022###
# bats.time.2<-ggplot(data=bats.time,
#        aes(x=monthN,
#            y=rel_freq,
#            color=AUTO.ID) )+
#   geom_line()+
#   facet_wrap(~year)+
#   labs(title = 'Number of Total Calls Per Species',
#        subtitle = "From 2017-2021",
#        x = 'Year', y = 'Number of Calls')+
#     scale_x_continuous(breaks = 1:12)
# #Using plotly to create a hover function
# ggplotly(bats.time.2, hovertemplate = paste())
# 
# ########Graphs for long term tab#########
# #Average temperature for all years
# temp_graph<-ggplot(data=df.2, aes(x=Month, y=AvgTemp_f, group=Year, color=Year))+
#   geom_line()+
#   labs(title = 'Overall Averages for Temperature ', caption = 'Sewanee Bat Study. DataLab 2022', y='Temperature (째F)')+
#   scale_x_continuous(breaks = 1:12)
# 
# #Using plotly to create a hover function
# ggplotly(temp_graph, hovertemplate = paste())  
```





# DASHBOARD PREP

```{r}
# Universal inputs (grouping, group, year, month)
# monthly.weather (vector - rain, wind, temperature)
# monthly.wrapVar (vector - none, year, management)

# stand-in input variables -----
input.grouping <- 'species'
input.group <- c("CORRAF","EPTFUS","LASBOR")
input.year <- c(2017:2022)
input.month <- month.abb[1:12]
# monthly.weather <- 'rain'
monthly.wrapVar <- 'none'

# colorblind palette -----
cbPalette <- c("#600047", "#d7a8d4", "#f5dfef", "#fe5f00","#fed457", "#c2c527", "#9ae825","#6f9c01", "#c5d5ea","#d3ffe2",  "#a2c2c6", "#087d93","#0c3660", "#133139")
```

```{r}
# basic filter -----
bats.sub <- bats %>% 
  filter( year %in% input.year, month %in% input.month ) %>% 
  rename( siteID = sensor )

# set grouping var column -----
if(input.grouping=='species'){ bats.sub <- bats.sub %>% mutate(group=AUTO.ID) }
if(input.grouping=='species group'){ bats.sub<-bats.sub%>%mutate(group=species_group) }
if(input.grouping=='cave dependency'){ bats.sub <- bats.sub %>% mutate(group=obligate) }

# group filter -----
bats.sub <- bats.sub %>% 
  filter( group %in% input.group )
```

```{r}
# set wrap var column -----
if(monthly.wrapVar=='year'){ bats.mon <- bats.sub %>% mutate(wrapV=year) }
if(monthly.wrapVar=='management'){ bats.mon <- bats.sub %>% mutate(wrapV=habitat) }

# summarize by appropriate groups -----
if(monthly.wrapVar == 'none'){
  bats.mon <- bats.sub %>% 
    group_by(monthN,month) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.mon <- bats.mon %>% 
    group_by(monthN,month,group) %>% 
    summarize( count=n(), relFreq=count/nSensors )
  bats.mon <- distinct(bats.mon)
} else {
  bats.mon <- bats.mon %>% 
    group_by(monthN,month,wrapV) %>% 
    mutate( nSensors = length(unique(siteID)) )
  bats.mon <- bats.mon %>% 
    group_by(monthN,month,wrapV,group) %>% 
    summarize( count=n(), relFreq=count/nSensors )
  bats.mon <- distinct(bats.mon)
}
```

```{r}
# make base plot -----
monthly.p <- ggplot( bats.mon ) +
  geom_line( aes(x=monthN, y=relFreq, color=group, text=paste("Group:",group)) ) +
  scale_x_discrete(limits=month.abb[1:12]) +
  scale_fill_manual(values = cbPalette) +
  labs(title="Monthly Bat Activity",
       x="Month", y ="Relative Frequency",
       caption="Sewanee Bat Study, DataLab 2022")

# wrap if appropriate -----
if(monthly.wrapVar != 'none'){
  monthly.p <- monthly.p + facet_wrap(~wrapV)
}

# plot with plotly ----
ggplotly( monthly.p, hovertemplate=paste() )
```





