---
title: "Long-Term Trends"
author: "Shelby Cline, Hallie Rutten"
date: '2022-06-27'
output: html_document
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# load libraries -----
library(ggthemes)
library(plotly)

# basic read -----
source('Read-bats.R')

# sensor data read -----
source('Read-sensorDates.R')
  
# join bats and sensor site data -----
bats <- left_join(bats,sensorDates, by=c('siteID','DATE'))

No.ID = c("Noise", "no.ID")

# bat species -----
library(readxl)
batspecies <- read_excel("../BatSpecies.xlsx")
#left join the 2 datasets
bats<- left_join(bats,batspecies, by="AUTO.ID")

# group common names -----
bats <- bats %>% 
  mutate( group_common = ifelse(ID_group=="MYOTIS", "Genus Myotis", Common),
          group_common = ifelse(ID_group=="EPTFUS.LASNOC",
                                "Big Brown Bat/Silver-haired Bat",group_common),
          group_common = ifelse(ID_group=="LASBOR.NYCHUM",
                                "Red Bat/Evening Bat", group_common) )

# group scientific names -----
bats <- bats %>% 
  mutate( group_species = ifelse(ID_group=="MYOTIS", "Myotis species", Scientific),
          group_species = ifelse(ID_group=="EPTFUS.LASNOC",
                                "Eptesicus fuscus/Lasionycteris noctivagans", group_species),
          group_species = ifelse(ID_group=="LASBOR.NYCHUM",
                                "Lasiurus borealis/Nycticeius humeralis", group_species) )

# daily weather data -----
weather.daily <- read_xlsx("../SUD Weather Station.xlsx") %>%
  rename( DATE = "Timestamp*",
          AvgTemp='Air temp Avg (C)',
          AvgWind='Wind Speed Avg (high) (m/S)' ) %>% 
  select( DATE, AvgTemp, AvgWind )

# hourly weather data -----
weather.hourly <- read_xlsx("../SUD Weather Station.xlsx", sheet=2) %>% 
  rename( AvgTemp = `Air Temp Avg (C)`,
          MaxWind = `wind speed (high) (m/s)`,
          MinWind = `wind speed (low) (m/s)`,
          rain = `Rain (mm)` ) %>% 
  mutate( DATE = date(Timestamp),
          year=year(Timestamp),
          month=month.abb[month(Timestamp)],
          hour=hour(Timestamp),
          AvgWind = (MaxWind+MinWind)/2 ) %>% 
  select( DATE, year, month, hour, AvgWind, AvgTemp)

# recorded rain data -----
rain.hourly <- read_xlsx("../SUD Weather Station.xlsx", sheet = 3) %>% 
  rename( rain.intensity = `Rain Intensity (mm/sec)` ) %>% 
  mutate( DATE = date(Timestamp),
          year=year(Timestamp),
          month=month.abb[month(Timestamp)],
          hour=hour(Timestamp) ) %>% 
  select(-Timestamp)

# weather join -----
weather <- left_join( weather.hourly, rain.hourly, by=c('DATE','year','month','hour') )
```

# Long-Term (yearly) and Climate (temperature/weather) Trends

This is the main graph


```{r, message=FALSE, warning=FALSE}
# want to create a column of cave obligates versus non-cave obligates to observe their activity

#take the total number of non cave bats divided by the number of cave dwelling bats in the whole year 
cave_obligate = c('PERSUB', 'MYOLEI', 'MYOAUS', 'MYOLUC', 'MYOSOD', 'MYOGRI', 'MYOSEP')
non_cave_obligate = c('LASBOR', 'NYCHUM', 'EPTFUS', 'LASNOC', 'LASCIN', 'CORRAF')
cave_ob <- bats %>%
  mutate(`cave obligate?` = AUTO.ID %in% cave_obligate) %>%
  filter(! AUTO.ID %in% No.ID) %>% 
  group_by(year, `cave obligate?`) %>% 
  mutate(tot_bat = n()) 
```

```{r, message=FALSE, warning=FALSE}
# to make this graph as accurate as possible, we put the proportion of CO bats in december over total NCO bats over time, and then vice versa to graph
cave_ob <- cave_ob %>% 
  group_by(monthN, `cave obligate?`, year) %>%
  summarize(prop_bat = n()/tot_bat) %>% 
  filter(monthN == 12)

ggplot(data = cave_ob,
       aes(x = year,
           y = prop_bat,
           color = `cave obligate?`))+
  geom_line()+
  labs(title = "Bat Activity in All Recorded Decembers",
       subtitle = "With Cave Obligate Bats vs. Non-Cave Obligate Bats, 
Weighted by Proportion to Total Recordings",
       x = "Year",
       y = "Bat Activity")
# theres a sharp dip in frequencies of both bats in 2020. interesting.
```

Looking into making species group columns (moved to Read-bats.R)

```{r, EVAL=FALSE}
EPTFUS.LASNOC = c("EPTFUS", "LASNOC")
LASBOR.NYCHUM = c('LASBOR', "NYCHUM")
bats <- bats %>% 
  mutate(species_group = ifelse(grepl("^MYO", AUTO.ID), "MYOTIS", AUTO.ID),
         species_group = ifelse(AUTO.ID %in% EPTFUS.LASNOC, "EPTFUS.LASNOC", species_group),
         species_group = ifelse(AUTO.ID %in% LASBOR.NYCHUM, "LASBOR.NYCHUM", species_group))
  
```

### Species frequencies by date

```{r, message=FALSE, warning=FALSE}
# account for number of sensors active on each date -----
bats.daily <- bats %>%
  group_by(DATE) %>%
  mutate( nSensors = length(unique(siteDate)) )
bats.daily <- bats.daily %>%
   filter(! AUTO.ID %in% No.ID) %>%
  group_by(DATE,AUTO.ID) %>%
  summarize( count = n(),
             relFreq = count/nSensors )
bats.daily <- distinct(bats.daily)

# wanting to graph just to see what they all look like over time
ggplot(data = bats.daily %>% filter(AUTO.ID != 'Noise')) +
         geom_line(aes( x = DATE,
                 y = count,
                 color = AUTO.ID,
                 alpha = 0.7))
# now i would like to look at just MYOTIS species
ggplot(data = bats.daily %>% filter(AUTO.ID == 'MYOLUC'))+
  geom_line(aes(x = DATE,
                 y = count),
            color = 'blue') +
  labs(title = 'Little Brown Bat Frequencies',
       subtitle = 'Across all Available Years',
       x = 'Year',
       y = 'Frequency')
```










# DASHBOARD PREP:

### make dummy input variables

```{r, message=FALSE, warning=FALSE}
# Universal inputs (grouping, group, year, month)
# yearly.weather (vector - rain, wind, temperature)
# yearly.wrapVar (vector - none, management)
bad <- c('no.ID','Noise')

# stand-in input variables -----
input.grouping <- 'species group'
input.group <- unique(bats$group_common)
input.group <- input.group[-which(input.group%in%bad)]
input.year <- c(2017:2021)
input.month <- month.abb[1:12]
yearly.wrapVar <- 'none'
yearly.weather <- c("rain","wind","temperature")

# colorblind palette -----
cbPalette <- c("#600047", "#d7a8d4", "#f5dfef", "#fe5f00","#fed457", "#c2c527", "#9ae825","#6f9c01", "#c5d5ea","#d3ffe2",  "#a2c2c6", "#087d93","#0c3660", "#133139")
```

### filter data as appropriate

```{r, message=FALSE, warning=FALSE}
# basic filter -----
bats.sub <- bats %>% 
  filter( year %in% input.year, month %in% input.month )

# set grouping var column -----
if(input.grouping=='species'){ 
  bats.sub <- bats.sub %>% mutate( group=Common, species=Scientific ) }
if(input.grouping=='species group'){ 
  bats.sub<-bats.sub %>% mutate( group=group_common, species=group_species) }
if(input.grouping=='cave dependency'){ 
  bats.sub <- bats.sub %>% mutate( group=obligate, species=obligate ) }

# group filter -----
bats.sub <- bats.sub %>% 
  filter( group %in% input.group )

# weather filter -----
weather.sub <- weather %>% 
  filter( year %in% input.year, month %in% input.month )
```

### perform activity and weather calculations

```{r, message=FALSE, warning=FALSE}
# base weather data -----
weather.yr <- weather.sub %>% 
  group_by(year) %>% 
  summarize( AvgTemp = mean(AvgTemp, na.rm=TRUE),
             AvgWind = mean(AvgWind, na.rm=TRUE),
             rain.intensity = mean(rain.intensity, na.rm=TRUE))

# set wrap var column -----
if(yearly.wrapVar=='management'){ bats.yr <- bats.sub %>% mutate(wrapV=habitat) }

# summarize by appropriate groups -----
if(yearly.wrapVar == 'none'){
  bats.yr <- bats.sub %>% 
    group_by(year) %>% 
    mutate( nSensors = length(unique(siteDate)) )
  bats.yr <- bats.yr %>% 
    group_by(year,group,species) %>% 
    summarize( count=n(), relFreq=count/nSensors )
  bats.yr <- distinct(bats.yr)
} else {
  bats.yr <- bats.yr %>% 
    group_by(year,wrapV) %>% 
    mutate( nSensors = length(unique(siteDate)) )
  bats.yr <- bats.yr %>% 
    group_by(year,wrapV,group,species) %>% 
    summarize( count=n(), relFreq=count/nSensors )
  bats.yr <- distinct(bats.yr)
}

# scale weather data -----
# W = W*(maxA/maxW)
temp.ratio <- max(bats.yr$relFreq)/max(weather.yr$AvgTemp)
wind.ratio <- max(bats.yr$relFreq)/max(weather.yr$AvgWind)
rain.ratio <- max(bats.yr$relFreq)/max(weather.yr$rain.intensity)
weather.yr <- weather.yr %>% 
  mutate( AvgTemp = AvgTemp*temp.ratio,
          AvgWind = AvgWind*wind.ratio,
          rain.intensity = rain.intensity*rain.ratio )
```

### Make plot

```{r, message=FALSE, warning=FALSE}
# make base plot -----
yearly.p <- ggplot() +
  scale_fill_manual(values = cbPalette) +
  labs(title="Yearly Bat Activity",
       x="Year", y ="Relative Frequency",
       caption="Sewanee Bat Study, DataLab 2022",
       color="Common Name")

# add weather -----
if('rain' %in% yearly.weather){
  yearly.p <- yearly.p + 
    geom_area( data=weather.yr, aes(x=year, y=rain.intensity), fill='blue', alpha=0.1 )
}
if('wind' %in% yearly.weather){
  yearly.p <- yearly.p + 
    geom_area( data=weather.yr, aes(x=year, y=AvgWind), fill='yellow', alpha=0.1 )
}
if('temperature' %in% yearly.weather){
  yearly.p <- yearly.p + 
    geom_area( data=weather.yr, aes(x=year, y=AvgTemp), fill='red', alpha=0.1 )
}

# add bat activity -----
yearly.p <- yearly.p +
  geom_line( data=bats.yr, aes(x=year, y=relFreq, color=group) )

# wrap if appropriate -----
if(yearly.wrapVar != 'none'){
  yearly.p <- yearly.p + facet_wrap(~wrapV, ncol=1)
}

# plot with plotly ----
#ggplotly( yearly.p, hovertemplate=paste() )
yearly.p + theme_clean()
```
